Install head will instal all the dependencies

diff --git a/hr b/hr
--- a/hr
+++ b/hr
@@ -12,7 +12,7 @@ BASEDIR=$(dirname $(readlink -f ${BASH_SOURCE[0]}))
 DEFAULT_HR_WORKSPACE=$HOME/hansonrobotics
 USER_DATA_DIR=$HOME/.hr
 HR_PREFIX=/opt/hansonrobotics
-HRTOOL_VERSION=0.3.13
+HRTOOL_VERSION=0.3.14
 
 OPENCOG_REPOS=(cogutils atomspace opencog ros-behavior-scripting relex external-tools)
 HR_REPOS=(blender_api_msgs blender_api chatbot motor_control sound ros_nmpt_saliency hr_msgs webui perception pi_vision performances ros_tts)
@@ -93,6 +93,9 @@ warn() {
 }
 error() {
     printf "${COLOR_ERROR}[ERROR] ${1}${COLOR_RESET}\n"
+}
+fail() {
+    printf "${COLOR_ERROR}[ERROR] ${1}${COLOR_RESET}\n" && return 1
 }
 
 SUDO=""
@@ -693,7 +696,12 @@ hr_stop() {
 
 ############# Functions #############
 install_head() {
-    install_head-deps
+    if [[ ! -z $GITHUB_TOKEN ]]; then
+        info "Installing head-hr-ext"
+        install_head-hr-ext || true
+    fi
+    install_head-deps-all
+    install_head-hr-msgs
     ssh -o StrictHostKeyChecking=no github.com 1>/dev/null 2>&1 || true
     get_head
     build_head
@@ -1217,6 +1225,7 @@ install_head-hr-ext() {
     if [[ ! -z $asset ]]; then
         local debname=$(basename $asset)
         curl -H "Accept: application/octet-stream" -L $(dirname $asset)?access_token=$GITHUB_TOKEN -o ${HR_CACHE}/$debname
+        $SUDO dpkg --info "${HR_CACHE}/${debname}" >/dev/null 2>&1 || fail "Can't get package" || return 1
         $SUDO dpkg -i "${HR_CACHE}/${debname}" || $SUDO apt-get install -f
         [[ -f ${HR_CACHE}/${debname} ]] && rm ${HR_CACHE}/${debname}
     else
@@ -1337,6 +1346,7 @@ install_head-ttsserver-voice-api() {
     if [[ ! -z $asset ]]; then
         local debname=$(basename $asset)
         curl -H "Accept: application/octet-stream" -L $(dirname $asset)?access_token=$GITHUB_TOKEN -o ${HR_CACHE}/$debname
+        $SUDO dpkg --info "${HR_CACHE}/${debname}" >/dev/null 2>&1 || fail "Can't get package" || return 1
         $SUDO dpkg -i "${HR_CACHE}/${debname}" || $SUDO apt-get install -f
         [[ -f ${HR_CACHE}/${debname} ]] && rm ${HR_CACHE}/${debname}
     else
