Report installation result

diff --git a/hr b/hr
--- a/hr
+++ b/hr
@@ -578,9 +578,13 @@ hr_install() {
         fi
         local func=install_${arg}
         info "Installing ${arg}"
-        eval $func $options
-        if [[ $? != 0 ]]; then
-            error "Install ${arg} failed return code $?"
+        local ret=0
+        ($func $options) || ret=$? && true
+        if [[ $ret != 0 ]]; then
+            error "Install ${arg} FAILED, return code $ret"
+            return $ret
+        else
+            info "Install ${arg} SUCCESS"
         fi
     done
 }
@@ -1042,6 +1046,7 @@ _install_deb_packages() {
     else
         error "${debname} is not debian package or broken. Please run again"
         rm ${HR_CACHE}/${debname}
+        return 1
     fi
 }
 
@@ -1063,6 +1068,10 @@ _install_latest_repo_release() {
     local force
     _parse_install_options $@
     local ver=$(get_latest_version $repo $prerelease)
+    if [[ -z $ver ]]; then
+        error "No version is found for repo \"${repo}\""
+        return 1
+    fi
     local assets=$(get_release_assets $repo $ver)
     if [[ ! -z $asset_name ]]; then
         for asset in ${assets[@]}; do
