Speed up updating repo

diff --git a/hr b/hr
--- a/hr
+++ b/hr
@@ -302,6 +302,7 @@ clone() {
 }
 
 _parse_repo_string() {
+    read_workspace
     local item=$1
     local ore owner repo dest workdir
     if [[ ! $item == *:* ]]; then
@@ -330,8 +331,17 @@ _get_repo() {
     fi
 }
 
-_update_repo() {
+_fetch_repo() {
     local args
+    mapfile -t args <<<"$(_parse_repo_string $1)"
+    local owner=${args[0]}
+    local repo=${args[1]}
+    local workdir=${args[2]}
+    info "Fetching [$owner/$repo]" && git -C ${workdir} fetch
+}
+
+_update_repo() {
+    local args branch
     mapfile -t args <<<"$(_parse_repo_string $1)"
     local owner=${args[0]}
     local repo=${args[1]}
@@ -341,17 +351,20 @@ _update_repo() {
         _get_repo $1
         return
     fi
+    info "Updating [${owner}/${repo}]"
     branch=$(git -C ${workdir} rev-parse --abbrev-ref HEAD)
     if [[ $branch != "master" ]]; then
         warn "[${repo}] Branch is \"${branch}\""
+    fi
+    if [[ $(git -C $workdir status -uno --porcelain|wc -c) != 0 ]]; then
+        warn "Plese commit the change(s) $workdir" 1>&2
+        echo $(git -C $workdir status -uno --porcelain) 1>&2
         return
     fi
-    info "Updating [${repo}]"
-    git -C ${workdir} pull origin $branch
+    git -C ${workdir} rebase origin/$branch >/dev/null || (warn "Update [${repo}] failed. Abort" && git -C ${workdir} rebase --abort && return)
     if [[ -f ${workdir}/.gitmodules ]]; then
         git -C ${workdir} submodule update --init --recursive
     fi
-    info "Updating [${repo}] is done"
 }
 
 _check_repo_changes() {
@@ -1231,7 +1244,7 @@ install_head-perception() {
 }
 
 install_head-pi-vision() {
-    install_head-opencv $@
+    #install_head-opencv $@
     local prerelease
     local force
     _parse_install_options $@
@@ -1780,6 +1793,7 @@ update_head() {
     if [[ $role  == "developer" ]]; then
         repos=(${repos[@]} ${HR_DEV_REPOS[@]})
     fi
+    parallel -j$(nproc) _fetch_repo ::: ${repos[@]}
     _update_repos ${repos[@]}
     info "Updating HEAD source code is done"
 }
@@ -1787,6 +1801,7 @@ update_head() {
 update_opencog() {
     read_workspace
     info "Updating OpenCog source code"
+    parallel -j$(nproc) _fetch_repo ::: ${OPENCOG_DEV_REPOS[@]}
     _update_repos ${OPENCOG_DEV_REPOS[@]}
     info "Updating OpenCog source code is done"
 }
@@ -2097,8 +2112,8 @@ if [[ ! $(lsb_release --codename --short) == "trusty" ]]; then
     exit 1
 fi
 
+export -f _get_repo _fetch_repo read_workspace _parse_repo_string clone info warn error
 if [[ ! $(readlink -f ${BASH_SOURCE[0]}) == $(readlink -f $0) ]]; then return; fi
 if [[ $# == 0 ]]; then show_help; exit 0; fi
-export -f _get_repo clone info warn error
 execute $@
 ############# End of Main #############
